version: "2"

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  mariadb:
  npm_data:
  npm_letsencrypt:
  mqtt_data:
  node-red_data:

services:
  db:
    container_name: db
    image: 'mariadb:10'
    restart: unless-stopped
    networks:
      - backend
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      TZ: Europe/Berlin
    volumes:
      - "mariadb:/var/lib/mysql"

  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port (accessible via NPM #loop):
      #- '81:81'
      # Add any other Stream port you want to expose
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
      TZ: Europe/Berlin
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  cert-watch:
    container_name: cert-watch
    build: ./cert-watch
    restart: unless-stopped
    networks:
      - backend
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      TZ: Europe/Berlin
    volumes:
      - npm_letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro

  mqtt:
    container_name: mqtt
    build: ./mqtt
    restart: unless-stopped
    networks:
      - backend
    environment:
      TZ: Europe/Berlin
    ports:
      - "10.14.0.5:1884:1884"
      - "8883:8883"
      - "8884:8884"
    volumes:
      - ./mqtt-config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - npm_letsencrypt:/etc/letsencrypt:ro

  node-red:
    container_name: node-red
    image: nodered/node-red
    restart: unless-stopped
    networks:
      - backend
    environment:
      NODE_RED_ENABLE_PROJECTS: true
      TZ: Europe/Berlin
    volumes:
      - node-red_data:/data
    user: node-red

  nextcloud_divera_bridge:
    container_name: nextcloud_divera_bridge
    image: ghcr.io/ff-woernitz/nextcloud_divera_bridge:master
    restart: unless-stopped
    networks:
      - backend
    environment:
      TZ: Europe/Berlin

######### Not in use yet
#  web-public:
#    container_name: web-public
#    build: ./webserver-public
#    restart: unless-stopped
#    networks:
#      - backend
#    environment:
#      TZ: Europe/Berlin
#    volumes:
#      - "/opt/www-public:/var/www/html/"
#    depends_on:
#      - db