# Config file for mosquitto
#
# See mosquitto.conf(5) for more information.

per_listener_settings true

user mosquitto

# =================================================================
# Persistence
# =================================================================

autosave_interval 60

persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data

# =================================================================
# Logging
# =================================================================

log_dest stdout

log_type error
log_type warning
log_type notice
log_type information
log_type subscribe

connection_messages true
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# =================================================================
# Listeners
# =================================================================

### Public MQTT START:
listener 8883
protocol mqtt

listener_allow_anonymous false

password_file /mosquitto/config/listener_public/passwd
acl_file /mosquitto/config/listener_public/acl
### Public MQTT END

### Public WS START:
listener 8884
protocol websockets

listener_allow_anonymous false

password_file /mosquitto/config/listener_public/passwd
acl_file /mosquitto/config/listener_public/acl
### Public WS END

### Private MQTT START:
listener 1884
protocol mqtt

listener_allow_anonymous false

password_file /mosquitto/config/listener_private/passwd
acl_file /mosquitto/config/listener_private/acl
### Private MQTT END

### Docker START:
listener 1883
protocol mqtt
listener_allow_anonymous true
### Docker END