volumes:
  grafana-data:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.ffw-it.de/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.ffw-it.de/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.ffw-it.de/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.ffw-it.de/application/o/grafana/end-session/"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Admin') && 'Admin' || contains(groups[*], 'IT') && 'Editor' || 'Viewer'"
      GF_SERVER_ROOT_URL: "https://grafana.vpn.ffw-it.de"
      TZ: Europe/Berlin
    env_file:
      - env/grafana.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.vpn.ffw-it.de`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.middlewares=vpn-whitelist@file"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
