volumes:
  node-red_data:

services:
  node-red:
    container_name: node-red
    image: nodered/node-red
    restart: unless-stopped
    networks:
      - backend
    environment:
      NODE_RED_ENABLE_PROJECTS: true
      TZ: Europe/Berlin
    volumes:
      - node-red_data:/data
    user: node-red
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red-owntracks.rule=Host(`owntracks-flow.ffw-it.de`) && Path(`/api-public/owntracks`)"
      - "traefik.http.routers.node-red-owntracks.entrypoints=websecure"
      - "traefik.http.routers.node-red-owntracks.tls=true"
      - "traefik.http.routers.node-red-owntracks.middlewares=authorized-owntrack-users@file"
      - "traefik.http.routers.node-red-public-api.rule=Host(`flow-api.ffw-it.de`) && PathRegexp(`^/api-public/[a-zA-Z0-9_-]+$`)"
      - "traefik.http.routers.node-red-public-api.entrypoints=websecure"
      - "traefik.http.routers.node-red-public-api.tls=true"
      - "traefik.http.routers.node-red-public-api.middlewares=authorized-owntrack-users@file"
      - "traefik.http.routers.node-red.rule=Host(`flow.vpn.ffw-it.de`)"
      - "traefik.http.routers.node-red.entrypoints=websecure"
      - "traefik.http.routers.node-red.middlewares=vpn-whitelist@file,sso-auth@file"
      - "traefik.http.routers.node-red.tls=true"
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"

      - "com.centurylinklabs.watchtower.monitor-only=true"
