include:
  - path: compose/traefik.yaml
    project_directory: .
  - path: compose/watchtower.yaml
    project_directory: .
  - path: compose/db.yaml
    project_directory: .
  - path: compose/phpmyadmin.yaml
    project_directory: .
  - path: compose/mqtt.yaml
    project_directory: .
  - path: compose/node-red.yaml
    project_directory: .
  - path: compose/nextcloud_divera_bridge.yaml
    project_directory: .
  - path: compose/collabora.yaml
    project_directory: .
  - path: compose/hedgedoc.yaml
    project_directory: .
  - path: compose/vaultwarden.yaml
    project_directory: .
  - path: compose/rustdesk.yaml
    project_directory: .
  - path: compose/influxdb.yaml
    project_directory: .
  - path: compose/grafana.yaml
    project_directory: .
  - path: compose/web-public.yaml
    project_directory: .

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  auth:
    name: auth_public
    external: true


volumes:
  mariadb:
  traefik-certs-data:
  mqtt_data:
  node-red_data:
  hedgedoc-data:
  vaultwarden-data:
  rustdesk-data:
  influxdb-config:
  influxdb-data:
  grafana-data:
