http:
  middlewares:
    redirect-homepage:
      redirectRegex:
        regex: "(.)*"
        replacement: "https://ff-woernitz.de"
  routers:
    router-homepage:
      rule: "Host(`ffw-it.de`)"
      entrypoints: websecure
      middlewares: redirect-homepage@file
      tls: true
      service: "noop@internal"